[package]
name = "storybook_yew_app"
version = "0.1.0"
edition = "2021"

[dependencies]
yew_app_core = { path="../yew_app_core" }
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew.git" }