[serve]
# The address to serve on LAN.
address = "127.0.0.1"
# The address to serve on WAN.
# address = "0.0.0.0"
# The port to serve on.
port = 8001

[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = ["../yew_app_core/src/components"]